/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The service is up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            /** @example v1 */
                            apiVersion: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filter capabilities of the configured backend
         * @description Flat dotted capability keys (for example `orderBy.sentAt`,
         *     `stringLookups.includes`). Consumers use this to hide sorting and
         *     filtering affordances the backend cannot honour. Missing keys mean
         *     "supported".
         *
         *     Only capabilities a client can act on appear here. Capabilities that
         *     describe how the server talks to its backend — the `pagination.*`
         *     namespace, which reports how the backend numbers its pages — are filtered
         *     out, because the API's own `page` parameter is 1-indexed either way and a
         *     client that saw them might convert a second time.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Capability map. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                [key: string]: boolean;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications
         * @description Filters are combined with AND. String filters (`bodyTemplate`,
         *     `subjectTemplate`, `contextName`) are matched with the most precise
         *     lookup the backend supports: case-insensitive `includes` when available,
         *     otherwise a case-insensitive exact match, otherwise a plain equality
         *     match. Ordering defaults to `createdAt desc`, and is dropped when the
         *     backend reports it cannot order by the requested field.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description 1-indexed page number: `page=1` is the first page. Translating this to
                     *     the backend's own numbering is the server's job.
                     */
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                    status?: components["schemas"]["NotificationStatus"];
                    notificationType?: components["schemas"]["NotificationType"];
                    adapterUsed?: string;
                    userId?: string;
                    bodyTemplate?: string;
                    subjectTemplate?: string;
                    contextName?: string;
                    tenant?: string;
                    /** @description Notifications pinned to this template version. Unpinned notifications never match, since a null version is not version zero. */
                    requestedTemplateVersion?: number;
                    /** @description Notifications that rendered this template version. Notifications that have not been sent, and those whose renderer has no versions, never match. */
                    usedTemplateVersion?: number;
                    createdAtFrom?: string;
                    createdAtTo?: string;
                    sentAtFrom?: string;
                    sentAtTo?: string;
                    orderByField?: "sendAfter" | "sentAt" | "readAt" | "createdAt" | "updatedAt";
                    orderByDirection?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["NotificationPage"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications awaiting send */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description 1-indexed page number: `page=1` is the first page. Translating this to
                     *     the backend's own numbering is the server's job.
                     */
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["NotificationPage"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/future": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications scheduled for the future */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description 1-indexed page number: `page=1` is the first page. Translating this to
                     *     the backend's own numbering is the server's job.
                     */
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["NotificationPage"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/one-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List one-off notifications */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description 1-indexed page number: `page=1` is the first page. Translating this to
                     *     the backend's own numbering is the server's job.
                     */
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["NotificationPage"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one notification with its context payloads
         * @description Looks the id up as a user notification first, then as a one-off one.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["notificationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The notification. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["NotificationDetail"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Render the notification's templates
         * @description Fetches the body and subject templates from the template source at the
         *     commit SHA persisted with the notification, then renders them with the
         *     stored context (or regenerates the context when none was stored).
         *     Notifications that are still `PENDING_SEND` and have no stored SHA fall
         *     back to the current `main` commit.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["notificationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rendered templates. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["NotificationPreview"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /**
                 * @description No commit SHA is available for this notification, so its templates
                 *     cannot be resolved (`PREVIEW_UNAVAILABLE`).
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /**
                 * @description The template source could not be reached, or refused the request —
                 *     for example a rate limit, a revoked token, or a template file that
                 *     does not exist at that commit (`UPSTREAM_ERROR`).
                 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend a notification
         * @description Creates a new notification based on an existing one. Only user
         *     notifications that have already been sent or failed can be resent.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["notificationId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Reuse the context stored with the original notification
                         *     instead of regenerating it from current data.
                         * @default false
                         */
                        useStoredContext?: boolean;
                    };
                };
            };
            responses: {
                /** @description The newly created notification. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UserNotification"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /**
                 * @description The notification cannot be resent — it does not exist, is a one-off
                 *     notification, or is scheduled for the future (`CONFLICT`).
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a pending notification */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["notificationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The notification was cancelled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                status: components["schemas"]["NotificationStatus"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description The notification is not in `PENDING_SEND` status (`CONFLICT`). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        NotificationStatus: "PENDING_SEND" | "SENT" | "FAILED" | "READ" | "CANCELLED";
        /** @enum {string} */
        NotificationType: "EMAIL" | "SMS" | "PUSH" | "IN_APP";
        NotificationAttachment: {
            id: string;
            filename: string;
            contentType: string;
            size: number;
            description?: string;
        };
        NotificationBase: {
            id: string;
            /**
             * @description Discriminates the two notification variants.
             * @enum {string}
             */
            kind: "user" | "one-off";
            notificationType: components["schemas"]["NotificationType"];
            title: string | null;
            contextName: string;
            status: components["schemas"]["NotificationStatus"];
            /** Format: date-time */
            sendAfter: string | null;
            /** Format: date-time */
            sentAt: string | null;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string | null;
            /** Format: date-time */
            updatedAt: string | null;
            adapterUsed: string | null;
            bodyTemplate: string;
            subjectTemplate: string | null;
            gitCommitSha: string | null;
            /** @description The template version this notification asked for, pinned when it was created or updated. Null means it was left unpinned and renders whatever version is current at send time. Always null when the service's template renderer has no versions. */
            requestedTemplateVersion: number | null;
            /** @description The template version the renderer reported after the notification was sent. Null until it has been sent, and always null when the template renderer has no versions. On an unpinned notification this is the only record of what went out. */
            usedTemplateVersion: number | null;
            tenant: string | null;
        };
        UserNotification: components["schemas"]["NotificationBase"] & {
            /** @enum {string} */
            kind?: "user";
            userId: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "user";
        };
        OneOffNotification: components["schemas"]["NotificationBase"] & {
            /** @enum {string} */
            kind?: "one-off";
            emailOrPhone: string;
            firstName: string | null;
            lastName: string | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "one-off";
        };
        Notification: components["schemas"]["UserNotification"] | components["schemas"]["OneOffNotification"];
        NotificationDetailFields: {
            /** @description Context the notification was rendered with, when stored. */
            contextUsed: unknown;
            /** @description Parameters used to generate the context. */
            contextParameters: unknown;
            extraParams: unknown;
            attachments: components["schemas"]["NotificationAttachment"][];
        };
        NotificationDetail: (components["schemas"]["UserNotification"] & components["schemas"]["NotificationDetailFields"]) | (components["schemas"]["OneOffNotification"] & components["schemas"]["NotificationDetailFields"]);
        PaginatedNotifications: {
            data: components["schemas"]["Notification"][];
            page: number;
            pageSize: number;
            /**
             * @description True when the page came back full, meaning another page may exist.
             *     Backends are not required to report a total count.
             */
            hasMore: boolean;
        };
        NotificationPreview: {
            gitCommitSha: string;
            bodyTemplatePath: string;
            subjectTemplatePath: string | null;
            renderedBodyHtml: string;
            renderedSubjectHtml: string;
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "BAD_REQUEST" | "UNAUTHORIZED" | "NOT_FOUND" | "CONFLICT" | "PREVIEW_UNAVAILABLE" | "UPSTREAM_ERROR" | "INTERNAL_ERROR";
                message: string;
                /** @description Optional machine-readable context, such as field issues. */
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description A page of notifications. */
        NotificationPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PaginatedNotifications"];
            };
        };
        /** @description The request failed validation (`BAD_REQUEST`). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The API key is missing or wrong (`UNAUTHORIZED`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No such notification (`NOT_FOUND`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description 1-indexed page number: `page=1` is the first page. Translating this to
         *     the backend's own numbering is the server's job.
         */
        page: number;
        pageSize: number;
        notificationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
